export { default as Uim } from './Uim'
export { default as Adm } from './Adm'
export { default as Cim } from './Cim'
export { default as Dashboard } from './Dashboard'
export { default as Om } from './Om'
export { default as Category } from './Category'
